language: java
jdk:
  - openjdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE votingtest;'
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)