language: java
jdk:
  - openjdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE votingtest;'
env:
  global:
    - CODECOV_TOKEN=:c2e97f32-9469-4810-ad6e-d382b05c2fe8
after_success:
  - bash <(curl -s https://codecov.io/bash)